// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHv1lD8cT8oNxTAdPZXcIfMMqtYpEtMnU',
    appId: '1:333884394131:web:6da29aa83c50fc6380db66',
    messagingSenderId: '333884394131',
    projectId: 'task-checkin',
    authDomain: 'task-checkin.firebaseapp.com',
    storageBucket: 'task-checkin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmRtUl0U31K-BR9i-kjvO2lVLK5aceci0',
    appId: '1:333884394131:android:78aef0007fba9c3b80db66',
    messagingSenderId: '333884394131',
    projectId: 'task-checkin',
    storageBucket: 'task-checkin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiUGnE6ElcXijKPRzSmI9pyGVplpY3Vt0',
    appId: '1:333884394131:ios:cba8cb8bd892cbb080db66',
    messagingSenderId: '333884394131',
    projectId: 'task-checkin',
    storageBucket: 'task-checkin.firebasestorage.app',
    iosBundleId: 'com.example.checkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiUGnE6ElcXijKPRzSmI9pyGVplpY3Vt0',
    appId: '1:333884394131:ios:cba8cb8bd892cbb080db66',
    messagingSenderId: '333884394131',
    projectId: 'task-checkin',
    storageBucket: 'task-checkin.firebasestorage.app',
    iosBundleId: 'com.example.checkin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHv1lD8cT8oNxTAdPZXcIfMMqtYpEtMnU',
    appId: '1:333884394131:web:90eb0519ce18e17c80db66',
    messagingSenderId: '333884394131',
    projectId: 'task-checkin',
    authDomain: 'task-checkin.firebaseapp.com',
    storageBucket: 'task-checkin.firebasestorage.app',
  );
}
